trigger:
- none # Or your primary branch

variables:
  dockerHubServiceConnection: 'SCDocker' # Name of your Docker Hub service connection
  dockerHubUsername: 'maremilojkovic' # Your Docker Hub username (lowercase)
  imageName: 'friznaklik' # The name of your image on Docker Hub
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPushToDockerHub
  displayName: 'Build and Push Docker Image to Docker Hub'
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    pool:
      name: 'Default' # <- CHANGE THIS to the name of the pool your agent is in
    steps:
    - task: Docker@2
      displayName: 'Build and Push image to Docker Hub'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(dockerHubServiceConnection)' # Uses your Docker Hub service connection
        repository: '$(dockerHubUsername)/$(imageName)' # Correct format for Docker Hub: username/repository
        dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
        buildContext: '$(Build.SourcesDirectory)'
        # Pass build arguments to Dockerfile if needed for NEXT_PUBLIC_ variables
        arguments: |
          --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="$(NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_SECRET)" \
          --build-arg NEXT_PUBLIC_SITE_URL="$(NEXT_PUBLIC_SITE_URL_RUNTIME)" \
          --build-arg GOOGLE_API_KEY="$(GOOGLE_API_KEY_SECRET)""
