trigger:
- none # Or your primary branch

variables:
  dockerHubServiceConnection: 'SCDocker' 
  dockerHubUsername: 'maremilojkovic' 
  imageName: 'friznaklik' 
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPushToDockerHub
  displayName: 'Build and Push Docker Image to Docker Hub'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    pool:
      name: 'Default' # Ensure this is your correct agent pool
    steps:
    # --- START DEBUG STEP ---
    - script: |
        echo "Build.SourcesDirectory value is: $(Build.SourcesDirectory)"
        echo "Listing contents of Build.SourcesDirectory:"
        ls -la "$(Build.SourcesDirectory)" 
      displayName: 'Debug Print Build Context Path'
    # --- END DEBUG STEP ---

    - task: Docker@2
      displayName: 'Build image' 
      inputs:
        command: 'build' 
        containerRegistry: '$(dockerHubServiceConnection)' 
        repository: '$(dockerHubUsername)/$(imageName)' 
        dockerfile: '$(dockerfilePath)'
        tags: | # Tags to apply to the built image locally
          $(tag)
          latest
        buildContext: '$(Build.SourcesDirectory)' # This should be the path argument Docker needs
        # --- Re-added arguments on a single line ---
        arguments: '--build-arg ARG1=Value1 --build-arg NEXT_PUBLIC_SITE_URL=$(PUBLIC_SITE_URL)'

    - task: Docker@2
      displayName: 'Push image to Docker Hub' 
      inputs:
        command: 'push' 
        containerRegistry: '$(dockerHubServiceConnection)' 
        repository: '$(dockerHubUsername)/$(imageName)' 
        tags: | # Specify which tags to push
          $(tag)
          latest
        # No need for dockerfile, buildContext, or arguments for push
