services:
  app:
    image: maremilojkovic/friznaklik:latest 
    container_name: friznaklik_app_prod
    restart: always 
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      db: 
        condition: service_healthy 
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_WEBHOOK_SECRET: ${CLERK_WEBHOOK_SECRET} 
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} 
      NEXT_PUBLIC_CLERK_DOMAIN: ${NEXT_PUBLIC_CLERK_DOMAIN}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL} 
      GOOGLE_API_KEY: ${GOOGLE_API_KEY} 
      NODE_ENV: production 