# docker-compose.yml (Base Configuration)
# Defines common services and networks/volumes

version: '3.8' # Specify compose file version (optional but good practice)

services:
  db:
    image: postgres:15-alpine 
    container_name: friznaklik_db
    restart: always
    environment:
      # These will be read from the .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    ports:
      - "${POSTGRES_PORT:-5432}:5432" 
    healthcheck: # Optional: Add healthcheck for DB readiness
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Define the named volume for data persistence
